version: '3.8'
services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - '3001:3000' # Optional: Only needed if you want to access the app directly for debugging

  nginx:
    build: ./infra/nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - portfolio
    links:
      - portfolio
