import {} from '@dredge/assets/fish';
import {
  BagOfDoubloonsImage,
  BaitBucketImage,
  BigBagOfDoubloonsImage,
  BoltOfClothImage,
  BrokenSpectaclesImage,
  ChunkOfFleshImage,
  DogTagsImage,
  DoubloonImage,
  LumberImage,
  MetalScrapsImage,
  PackedExplosivesImage,
  RefinedMetalImage,
  ResearchPartImage,
  SextantImage,
} from '@dredge/assets/items';
import { GameItem } from '@dredge/types';

export const itemData: GameItem[] = [
  {
    id: 'bait-bucket',
    name: 'Bait Bucket',
    image: BaitBucketImage,
    width: 1,
    height: 2,
    shape: [[1], [1]],
  },
  {
    id: 'dog-tags',
    name: 'Dog Tags',
    image: DogTagsImage,
    width: 1,
    height: 2,
    shape: [[1], [1]],
  },
  {
    id: 'bolt-of-cloth',
    name: 'Bolt of Cloth',
    image: BoltOfClothImage,
    width: 1,
    height: 2,
    shape: [[1], [1]],
  },
  {
    id: 'metal-scraps',
    name: 'Metal Scraps',
    image: MetalScrapsImage,
    width: 2,
    height: 2,
    shape: [
      [1, 1],
      [1, 1],
    ],
  },
  {
    id: 'lumber',
    name: 'Lumber',
    image: LumberImage,
    width: 3,
    height: 1,
    shape: [[1, 1, 1]],
  },
  {
    id: 'packed-explosives',
    name: 'Packed Explosives',
    image: PackedExplosivesImage,
    width: 1,
    height: 2,
    shape: [[1], [1]],
  },
  {
    id: 'research-part',
    name: 'Research Part',
    image: ResearchPartImage,
    width: 1,
    height: 1,
    shape: [[1]],
  },
  {
    id: 'refined-metal',
    name: 'Refined Metal',
    image: RefinedMetalImage,
    width: 2,
    height: 2,
    shape: [
      [0, 1],
      [1, 1],
    ],
  },
  {
    id: 'chunk-of-flesh',
    name: 'Chunk of Flesh',
    image: ChunkOfFleshImage,
    width: 2,
    height: 3,
    shape: [
      [1, 1],
      [1, 1],
      [1, 1],
    ],
  },
  {
    id: 'broken-spectacles',
    name: 'Broken Spectacles',
    image: BrokenSpectaclesImage,
    width: 2,
    height: 1,
    shape: [[1, 1]],
  },
  {
    id: 'doubloon',
    name: 'Doubloon',
    image: DoubloonImage,
    width: 1,
    height: 1,
    shape: [[1]],
  },
  {
    id: 'bag-of-doubloons',
    name: 'Bag of Doubloons',
    image: BagOfDoubloonsImage,
    width: 1,
    height: 2,
    shape: [[1], [1]],
  },
  {
    id: 'big-bag-of-doubloons',
    name: 'Big Bag of Doubloons',
    image: BigBagOfDoubloonsImage,
    width: 2,
    height: 2,
    shape: [
      [1, 1],
      [1, 1],
    ],
  },
  {
    id: 'sextant',
    name: 'Sextant',
    image: SextantImage,
    width: 2,
    height: 2,
    shape: [
      [1, 1],
      [1, 1],
    ],
  },
] as const;
