// GENERATED by scripts/copy-mediapipe-wasm.mjs -- do not edit by hand.
// public/ is served immutable for a year with no content hash, so the wasm
// runtime lives in a version-stamped directory.
export const MEDIAPIPE_WASM_DIR = 'mediapipe/wasm-0.10.17';
