export { default as BlueMackerelImage } from './blue-mackerel.webp';
export { default as CodImage } from './cod.webp';
export { default as ArrowSquidImage } from './arrow-squid.webp';
export { default as GreyEelImage } from './grey-eel.webp';
export { default as GulfFlounderImage } from './gulf-flounder.webp';
export { default as BlackGrouperImage } from './black-grouper.webp';
export { default as StingrayImage } from './stingray.webp';
export { default as SailfishImage } from './sailfish.webp';
export { default as BronzeWhalerImage } from './bronze-whaler.webp';
