name: Notify Container

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Container
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"event": "push"}' https://scottjhetrick.com/webhook
